@echo off
REM Usage: prepare-mario-maker-llm.bat <input> [seed]
REM <input> is a path to a .txt ASCII level file or a folder of .txt files
REM [seed]  is optional, defaults to 0
REM
REM Identical to prepare-mario-maker.bat except captions are generated by a
REM local Ollama LLM (qwen2.5:14b) instead of the simple tile-presence method.
REM Ollama is started automatically if not already running.
cd ..

set INPUT=%1
if "%INPUT%"=="" (
    echo ERROR: Must provide input path as first argument.
    exit /b 1
)

set MODEL=%2
if "%MODEL%"=="" set MODEL=qwen2.5:14b

set SEED=%3
if "%SEED%"=="" set SEED=0

set GAME=MM
set TYPE=regular
set TILESET=extended_tiles.json

set RAW_OUTPUT=datasets\%GAME%_Levels-%TYPE%.json
set CAPTIONED_OUTPUT=datasets\%GAME%_LevelsAndCaptions-%TYPE%.json

REM -- Folder for the token-grid .txt files actually sent to the LLM, placed
REM    next to the input ASCII folder/file.
for %%I in ("%INPUT%") do set "INPUT_DIR=%%~dpI"
set LLM_ASCII_DIR=%INPUT_DIR%ascii_tokens

REM -- Ollama setup ---------------------------------------------------------
ollama list >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo Ollama not running. Starting ollama serve...
    start /min "" ollama serve
    echo Waiting for Ollama to initialise...
    timeout /t 6 /nobreak >nul
)

echo Pulling %MODEL% ^(no-op if already present^)...
ollama pull %MODEL%
if %ERRORLEVEL% neq 0 (
    echo ERROR: Failed to pull %MODEL%. Is Ollama running?
    exit /b 1
)

REM -- Pipeline ---------------------------------------------------------------
python build_dataset_with_ascii.py --input_file %INPUT% --output %RAW_OUTPUT% --tileset %TILESET% --sliding_window --stride 20
python MarioMaker_llm_captions.py --dataset %RAW_OUTPUT% --tileset %TILESET% --output %CAPTIONED_OUTPUT% --model %MODEL% --grid-format tokens --tileset-we mm2_tileset_we.json --ascii-output-dir "%LLM_ASCII_DIR%"
python split_mario_maker_data.py --json %CAPTIONED_OUTPUT% --seed %SEED%
python tokenizer.py save --json_file datasets\%GAME%_LevelsAndCaptions-%TYPE%-train.json --pkl_file datasets\%GAME%_Tokenizer-%TYPE%.pkl
python create_mario_maker_random_captions.py --json %CAPTIONED_OUTPUT% --output datasets\%GAME%_RandomTest-%TYPE%.json
